import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';
import { SigninComponent } from './pages/signin/signin.component';
import { SignupComponent } from './pages/signup/signup.component';
import { AboutComponent } from './pages/about/about.component';
import { ServiceComponent } from './pages/service/service.component';
import { EmployeeComponent } from './pages/employee/employee.component';
import { UserComponent } from './pages/user/user.component';
import { ContactUsComponent } from './pages/contacus/contactus.component';
import { StudentsComponent } from './pages/students/students.component';
import { OurTeamComponent } from './pages/ourteam/ourteam.component';
import { ProductComponent } from './pages/product/product.component';
import { TestimonialComponent } from './pages/testimonial/testimonial.component';
import { BlogsComponent } from './pages/blogs/blogs.component';
import { CourseComponent } from './pages/course/course.component';

export const routes: Routes = [
  { path: '', component: SigninComponent },
  { path: 'signup', component: SignupComponent },
  { path: 'home', component: HomeComponent },
  { path: 'about', component: AboutComponent },
  { path: 'service', component: ServiceComponent },
  { path: 'employee', component: EmployeeComponent },
  { path: 'user', component: UserComponent },
  { path: 'contactus', component: ContactUsComponent },
  { path: 'students', component: StudentsComponent },
  { path: 'ourteam', component: OurTeamComponent },
  { path: 'product', component: ProductComponent },
  { path: 'testimonial', component: TestimonialComponent },
  { path: 'blogs', component: BlogsComponent },
  { path: 'course', component: CourseComponent },
];
